definitions:
  entities.CreateTask:
    properties:
      description:
        type: string
      status:
        $ref: '#/definitions/entities.Status'
      title:
        type: string
    type: object
  entities.Status:
    enum:
    - TODO
    - DOING
    - DONE
    type: string
    x-enum-varnames:
    - TODO
    - DOING
    - DONE
  entities.StatusChangeRequest:
    properties:
      status:
        $ref: '#/definitions/entities.Status'
    type: object
  entities.Task:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        $ref: '#/definitions/entities.Status'
      title:
        type: string
    type: object
  entities.UpdateTask:
    properties:
      description:
        type: string
      status:
        $ref: '#/definitions/entities.Status'
      title:
        type: string
    type: object
  models.Status:
    enum:
    - TODO
    - DOING
    - DONE
    type: string
    x-enum-varnames:
    - TODO
    - DOING
    - DONE
  models.Task:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        $ref: '#/definitions/models.Status'
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      description: Get all tasks
      responses: {}
      summary: Get all tasks
      tags:
      - Task
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task object to be created
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/entities.CreateTask'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
      summary: Create a New Task
      tags:
      - Task
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a task by its ID
      parameters:
      - description: Task ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete Task by ID
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Get a task by its ID
      parameters:
      - description: Task ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Task'
      summary: Get Task by ID
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: Update a task by its ID
      parameters:
      - description: Task ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Task object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/entities.UpdateTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
      summary: Update Task by ID
      tags:
      - Task
  /tasks/status/{id}:
    patch:
      consumes:
      - application/json
      description: Change status of a task by ID
      parameters:
      - description: Task ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: Status object to be created
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/entities.StatusChangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Task'
      summary: Change Task Status
      tags:
      - Task
swagger: "2.0"
